CONSUMER_KEY: adasdas
CONSUMER_SECRET: asdsdfsdfsdsss
OAUTH_MWURI: https://meta.wikimedia.org/w
SESSION_COOKIE_SECURE: True
SESSION_REFRESH_EACH_REQUEST: False
PREFERRED_URL_SCHEME: https
SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:@localhost/wikifile
SQLALCHEMY_TRACK_MODIFICATIONS: False